//ejercicio 1 - area de triangulo 
//formula AT= (B + H)/2
//AT = area de triangulo 
//B = base 
//H = altura 
// """"""""""""""""

//cambia estos valores para probar el programa con otros datos.

const base = 90; //base del triangulo  (numerico)
const altura = 4; //altura del triangulo (numerico)

//aplicamos la formula del area; (base por altura dividido entre 2).
const areatriangulo = (base * altura) / 2;

// mostrar en consola los datos de entrada junto el resultado obtenido.
console.log ("==== area de un triangulo====");
console.log ("la base es: ", base); //imprime el valor de la base.
console.log ("la altura es: ", altura); //imprime el valor de la altura.
console.log("el area de un triangulo es: ", areatriangulo); //imprime el resultado final

